[supabase]
url = "https://ikfkfanfnbdlemkkcwnl.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZmtmYW5mbmJkbGVta2tjd25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2ODQ0MTksImV4cCI6MjA3NjI2MDQxOX0.Z-_emTDVVbuJ1roPBMRS8ElVJG6-QB3ZmRk12O0Qvb4"
